name: Project Triaging
description: A template for information to look for in an NGI project's resources
title: <PROJECT_NAME>
labels:
  - project
body:
  - type: textarea
    id: summary
    attributes:
      label: Short Summary
      description: A short description of the project (optional)
  - type: input
    id: website
    attributes:
      label: Website
      placeholder: https://foobar.com
  - type: textarea
    id: source
    attributes:
      label: Source repository
      placeholder: "- https://github.com/foo/foobar"
  - type: textarea
    id: nlnet
    attributes:
      label: NLnet page(s)
      description: >-
        Navigate to the [NLnet project list](https://nlnet.nl/project/) and add
        the links to related projects
      placeholder: "- https://nlnet.nl/project/<PROJECT_NAME>"
    validations:
      required: true
  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      value: |-
        - Usage Examples:
        - Build from source/Development:
        - Other:
  - type: textarea
    id: components
    attributes:
      label: Components
      description: >-
        Name of project component according to its type. Any specific **links or
        documentation** to this component should also be linked here.
      placeholder: |
        - CLI:
        - GUI:
        - Service/daemon:
        - Library:
        - Extensions:
        - Mobile:
  - type: textarea
    id: metadata
    attributes:
      label: Metadata
      value: |-
        - Language/Framework:
        - Dependency management:
        - Development envirnment:
          - [default.nix, flake.nix, devenv.nix, ...](<SOURCE_REPO_LINK>)
  - type: textarea
    id: nixos
    attributes:
      label: NixOS
      description: >-
        Go to the nixpkgs search pages for
        [packages](https://search.nixos.org/packages) and
        [services](https://search.nixos.org/options?) and check if anything
        related to the project is already packaged.
      value: |2
           - Packages:
             - [<NAME>](<SOURCE_LINK>)
           - Services:
             - [<NAME>](<SOURCE_LINK>)
  - type: textarea
    id: extra
    attributes:
      label: Extra Information
      description: >-
        Anything interesting or helpful for packaging the project like notes,
        issues or pull requests
