name: Test project demos

permissions: {}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        distro:
          - "archlinux:latest"
          - "debian:12"
          - "debian:unstable"
          - "ubuntu:24.04"
          - "ubuntu:24.10"
          - "ubuntu:25.04"
        project:
          - "Cryptpad"
          - "mitmproxy"

    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
        with: { persist-credentials: false }

      - uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3  #v17

      - name: Build projects overview
        run: nix build .#overview

      - name: Load Nix config
        run: |
          source ./result/ci/.env
          echo "NIX_CONFIG=$NIX_CONFIG" >> "$GITHUB_ENV"

      - name: Run and test demo
        env:
          DISTRO: ${{ matrix.distro }}
          PROJECT: ${{ matrix.project }}
          NIX_CONFIG: ${{ env.NIX_CONFIG }}
        run: >
          docker run
          --privileged
          --volume ./result:/overview
          --volume "$(pwd):/ngipkgs"
          -e DISTRO="$DISTRO"
          -e PROJECT="$PROJECT"
          "$DISTRO"
          /bin/bash -c "bash /ngipkgs/.github/workflows/test-demo.sh"
